apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: tetrisgame
  template:
    metadata:
      labels:
        app: tetrisgame
    spec:
      containers:
        - name: mycontainer
          image: yembulururajaneesh/tetrisgame:v2
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"      # baseline CPU request
              memory: 250Mi    # baseline memory request
            limits:
              cpu: "250m"      # max CPU limit
              memory: 500Mi    # max memory limit
          envFrom:
            - configMapRef:
                name: myconfigmap
            - secretRef:
                name: mysecret
