apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  DB_NAME: dGV0cmlzZGI=  
  DB_PORT: NTQzMg==  
  API_KEY: c2FtcGxlLWFwaS1rZXktMTIzNDU2Nzg5MA== 
  AUTH_TOKEN: c2FtcGxlLXRva2VuLWFiY2RlZjEyMzQ1Ng== 
